## Importing the library

In [1]:
import numpy as np

## Data Types

### Scalars

In [2]:
# creating a scalar, we use the 'array' in order to create any type of data type e.g. scalar, vector, matrix
s = np.array(5)
# visualizing the shape of a scalar, in the example below it returns an empty tuple which is normal
# a scalar has zero-length which in numpy is represented as an empty tuple
print(s.shape) 
# we can do operations on a scalar e.g addition
x = s + 3
print(x)

()
8


### Vectors

In [3]:
# creating a vector. we have to pass a list as input
v = np.array([1,2,3])
# visualizing the shape, a 3-long row vector. This can also be stored as a column vector
print(v.shape)
# access first element
v[1]
# access from second to last
v[1:]

(3,)


array([2, 3])

### Matrices

In [4]:
# creating a matrix, with a list of lists as input
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
# visualize shape, a 3 x 3 matrix
m.shape
# access from the second row, first two elements
m[1,:2]
# access elements from all rows from the third column
m[:,-1]

array([3, 6, 9])

### Tensors

In [5]:
# creating a 4-dimensional tensor
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
# visualize shape, this structure is going to be used a lot of times in PyTorch and other deep learning frameworks
t.shape
# access number 16, we have to pass through the dimensions by using multiple indices
# in order to get to the value
t[2][1][1][0]

16

### Changing shapes
Sometimes you'll need to change the shape of your data without actually changing its contents. For example, you may have a vector, which is one-dimensional, but need a matrix, which is two-dimensional.

In [6]:
# let's say we have a row vector
v = np.array([1,2,3,4])
v.shape

(4,)

In [7]:
# what if we wanted a 1x4 matrix instead but without re-declaring the variable
x = v.reshape(1,4) # specify the column size, then the row size
print(x)
x.shape

[[1 2 3 4]]


(1, 4)

In [8]:
# and we could change back to 4x1
x = x.reshape(4,1)
print(x)
x.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

#### Other way of changing shape
From Udacity: Those lines create a slice that looks at all of the items of `v` but asks NumPy to add a new dimension of size 1 for the associated axis. It may look strange to you now, but it's a common technique so it's good to be aware of it. 

In [9]:
# other ways to reshape using slicing which is a very common practice when working with numpy arrays
# this is essentially telling us slice the array, give me all the columns and put them under one column
x = v[None, :]
print(x)
x.shape

[[1 2 3 4]]


(1, 4)

In [10]:
# give me all the rows and put them in one column
x = v[:, None]
print(x)
x.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

### Element-wise operations

In [11]:
# performing a scalar addition
values = [1,2,3,4,5]
values = np.array(values) + 5
print(values)

[ 6  7  8  9 10]


In [12]:
# scalar multiplication, you can either use operators or functions
some_values = [2,3,4,5]
x = np.multiply(some_values, 5)
print(x)
y = np.array(some_values) * 5
print(y)

[10 15 20 25]
[10 15 20 25]


In [13]:
# set every element to 0 in a matrix
m = np.array([1,27,98, 5])
print(m)
# now every element in m is zero, no matter how many dimensions it has
m *= 0
print(m)

[ 1 27 98  5]
[0 0 0 0]


### Element-wise Matrix Operations
The **key** here is to remember that these operations work only with matrices of the same shape, 
if the shapes are different then we couldn't perform the addition as below

In [14]:
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])
a + b

array([[ 3,  7],
       [11, 15]])

### Matrix multiplication

### Important Reminders About Matrix Multiplication

- The number of columns in the left matrix must equal the number of rows in the right matrix.
- The answer matrix always has the same number of rows as the left matrix and the same number of columns as the right matrix.
- Order matters. Multiplying A•B is not the same as multiplying B•A.
- Data in the left matrix should be arranged as rows., while data in the right matrix should be arranged as columns.

In [15]:
m = np.array([[1,2,3],[4,5,6]])
n = m * 0.25

np.multiply(m,n) # m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

#### Matrix Product

In [16]:
# pay close attention to the shapes of the matrices
# the column of the left matrix must have the same value as the row of the right matrix
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b.shape)
c = np.matmul(a,b)
print(c)

(2, 4)
(4, 3)
[[ 70  80  90]
 [158 184 210]]


#### Dot Product
It turns out that the results of `dot` and `matmul` are the same if the matrices are two dimensional. However, if the dimensions differ then you should expect different results so it's best to check the documentation for [dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) and [matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul).

In [17]:
a = np.array([[1,2],[3,4]])
# two ways of calling dot product
np.dot(a,a)
a.dot(a)
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

### Matrix Transpose
If the original matrix is not a square then transpose changes its shape, technically we are swapping
e.g. 2x4 matrix to 4x2

#### Rule of thumb: you can transpose for matrix multiplication if the data in the original matrices was arranged in rows but doesn't always apply 
Stop and really think what is in your matrices and which should interact with each other

In [28]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(m)
print(m.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


NumPy does this without actually moving any data in memory - 
it simply changes the way it indexes the original matrix - so it’s quite efficient.

In [29]:
# let's do a transpose
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [30]:
# be careful with modifying data
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

Notice how it modified both the transpose and the original matrix, too! 

In [31]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

#### Real case example

In [32]:
# we have two matrices inputs and weights (essential concepts for Neural Networks)
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
print(inputs)
inputs.shape

[[-0.27  0.45  0.64  0.31]]


(1, 4)

In [33]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
print(weights)
weights.shape

[[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]]


(3, 4)

In [35]:
# let's try to do a matrix multiplication
np.matmul(inputs, weights)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

What happened was that our matrices were not compatible because the columns from our left matrix didn't equal the number of rows from the right matrix. So what do we do? We transpose but which one? That depends on what shape we want.

In [36]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [37]:
# in order for this to work we have to swap the order of our matrices
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

The two answers are transposes of each other, so which multiplication you use really just depends on the shape you want for the output.

### Numpy exercises

In [72]:
def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - input_array.min()

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / inputs_minus_min.max()

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[0] != m2.shape[1] and m1.shape[1] != m2.shape[0]:
        return False
    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)        
    else:
        return np.matmul(m2, m1) 
    
def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)

In [73]:
input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
